<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \Illuminate\Support\Facades\DB::table('products')->truncate();
        \Illuminate\Support\Facades\DB::table('products')->insert([
            //Áo nam đi biển
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'SEE YOU PIGMENT TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305200018_Pigment_SeeYou_WHT_1_large.jpg?v=1524526512',
                'price'=> 150000,
                'discount'=>0,
                'description'=>'Áo đi biển nam họa tiết chuối sành điệu',
                'detail'=>'Áo đi biển nam họa tiết chuối sành điệu: Chất liệu kate thấm hút ẩm tốt, dễ dàng giặt ủi đem lại
                cảm giác thoải mái và thông thoáng cho người sử dụng.Thiết kế cổ bẻ, tay ngắn cho phái mạnh tự tin đi biển',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'DEAD BEAT OLD TIME TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/304300146_OldTime_DeadBeat_BBLU_2_large.jpg?v=1524596609',
                'price'=> 150000,
                'discount'=>20,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'GREAT WHITE PREMIUM TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/304400156_BLK_1_large.jpg?v=1531510717',
                'price'=> 150000,
                'discount'=>20,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'MOVEMENT BLENDED TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305100022_SGREY_1_large.jpg?v=1531515378',
                'price'=> 50000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'BLENDED',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305100020_Blended_Avalon_JUN_2_large.jpg?v=1523924570',
                'price'=> 100000,
                'discount'=>30,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'STESS JACKET',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/313000089_Anorak_NoStress_WHT_2_large.jpg?v=1524525523',
                'price'=> 100000,
                'discount'=>30,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'SLEEVE TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/309000060_StockLS_SunUp_BLU_2_large.jpg?v=1524592995',
                'price'=> 100000,
                'discount'=>30,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'PREMIUM TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/304400139_Premium_SunUp_PBLU_2_large.jpg?v=1530291899',
                'price'=> 100000,
                'discount'=>30,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'STOCK TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/309000056_WHT_2_1024x1024_ebe0fba0-6c7f-46c0-bd5b-3869537b56dd_large.jpg?v=1525716966',
                'price'=> 100000,
                'discount'=>30,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'CLASSIC TEA',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/304400177M_BLK_1_copy_large.jpg?v=1525735327',
                'price'=> 100000,
                'discount'=>30,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'WORK DAY',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305200024_IBLU_1_large.jpg?v=1531786725',
                'price'=> 100000,
                'discount'=>30,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>1,
                'name'=>'PASSION',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/305200023_MUS_1_large.jpg?v=1532561558',
                'price'=> 100000,
                'discount'=>30,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Áo nữ đi biển
            [
                'categoryId'=>2,
                'collectionId'=>1,
                'name'=>'MORRISON TANK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/408400009_GCM_1_large.jpg?v=1532037589',
                'price'=> 100000,
                'discount'=>30,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'DIVE CUTOFF TANK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/403200031_BLKW_2_copy_large.jpg?v=1518653614',
                'price'=> 1500000,
                'discount'=>0,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>1,
                'name'=>'ARDAMA TRIBLEND TANK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/402100019_IND_1_large.jpg?v=1517442825',
                'price'=> 100000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>1,
                'name'=>'BASIC TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/404000048_WHT_2_copy_large.jpg?v=1518653891',
                'price'=> 200000,
                'discount'=>50,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'DIVER TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/404000062_WHT_1_large.jpg?v=1532036286',
                'price'=> 110000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'CALI TEE',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/404000061_DSD_2_large.jpg?v=1532035734',
                'price'=> 110000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'MEMORIAL STOW',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/407600012_YEL_2_copy_large.jpg?v=1518658297',
                'price'=> 110000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'ROSE SHRUNKEN',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/405000004_WHT_2_large.jpg?v=1532037927',
                'price'=> 110000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'ROSE STOW',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/407600021_PBU_2_large.jpg?v=1532038174',
                'price'=> 110000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'SWELL TD',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/404000053_BLKW_2_large.jpg?v=1517443742',
                'price'=> 110000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'SUNBURN',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/402100022_HEA_1_copy_large.jpg?v=1518653532',
                'price'=> 110000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>2,
                'collectionId'=>2,
                'name'=>'GRAVEYARD',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/401100024_GHE_1_large.jpg?v=1532037005',
                'price'=> 110000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Quần đi biển nam
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'BLACKWALL I',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_CAM_1_large.jpg?v=1532378454',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'BLACKWALL II',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_NAVYTOBACCO_1_large.jpg?v=1516836073',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'BLACKWALL III',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_NAVY_RED-1_large.jpg?v=1532104878',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'BLACKWALL IV',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_CAVIAR-1_large.jpg?v=1532045768',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'STOKEHOLD',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200037_BLACK-1_large.jpg?v=1524697048',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'LANDLOPER',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200036_BLACK_1_18801f16-b604-4dcb-bc8f-b98627d9eb54_large.jpg?v=1520011227',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'RANRI',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_CAM_1_copy_large.jpg?v=1520025805',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'ZUBIES I',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200034_NAVY_1_6e192388-7b3b-4154-b7f8-46a19ebbea46_large.jpg?v=1520009194',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'ZUBIES II',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200035_DENIM_1_large.jpg?v=1516836392',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'ZUBIES III',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200027_BLACKWHITE_1WEB_large.jpg?v=1499389981',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'BLACKWALL',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200027_BROWNRED_1_large.jpg?v=1532104770',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>1,
                'collectionId'=>2,
                'name'=>'LANDLOPER II',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/315200036_ARMY_1_large.jpg?v=1520011292',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Kính đi biển
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'EYEGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-6656-28-angle.jpg?sfvrsn=8f6de21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'EYEGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-5832-100-angle.jpg?sfvrsn=b176e21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'EYEGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/july-18/see-0533-423-angle.jpg?sfvrsn=d2fbe21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'EYEGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-8151-39-angle.jpg?sfvrsn=d365e21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'EYEGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/june-18/see-0529-106-angle.jpg?sfvrsn=806ce11b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'EYEGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/april-18-trunk-show/see-0523-c3176-angle.jpg?sfvrsn=aebce11b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'SUNGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-9287-32-angle.jpg?sfvrsn=4765e21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'SUNGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/august-18/see-9651-59-angle.jpg?sfvrsn=b366e21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'SUNGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/see-1832-31-angle.jpg?sfvrsn=62ece21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'SUNGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/see-1832-31-angle.jpg?sfvrsn=62ece21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'SUNGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/see-1832-31-angle.jpg?sfvrsn=62ece21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>3,
                'collectionId'=>2,
                'name'=>'SUNGLASSES',
                'images'=>'https://www.seeeyewear.com/images/default-source/product_images/july-18/see-9635-1-angle.jpg?sfvrsn=4fd4e21b_4',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Mũ đi biển
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'HUGH HAT',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000256_HUGO_HOT_LIME-1_large.jpg?v=1524766491',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'BEACHHEAD',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000250_CAMO_1_large.jpg?v=1516838110',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'BUCKET HAT',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000251_PEACH_1_large.jpg?v=1516838137',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'GAFFTOP HAT',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000251_PEACH_1_large.jpg?v=1516838137',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'MCGRATH SNAPBACK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000247_BLK_1_large.jpg?v=1517856892',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'YBARRA SNAPBACK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000245_NVY_1_large.jpg?v=1516837957',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'SHANGHAI TRUCKER',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000244_BLACK_1_large.jpg?v=1516837884',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'DRYDEN',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000243_NVY_1_large.jpg?v=1516837771',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'DOC',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000222_BLK_1_large.jpg?v=1499390326',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'TRIDENT TRUCKER',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000225_NVY_1_large.jpg?v=1517857304',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'TRIDENT SNAPBACK',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000226_BLK_1_large.jpg?v=1524766647',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>4,
                'collectionId'=>2,
                'name'=>'JOURNEYMAN',
                'images'=>'https://cdn.shopify.com/s/files/1/0476/6585/products/321000224_NAVYRED_1_large.jpg?v=1531787265',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            //Dép đi biển
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ],
            [
                'categoryId'=>5,
                'collectionId'=>2,
                'name'=>'',
                'images'=>'',
                'price'=> 10000,
                'discount'=>10,
                'description'=>'Hàng tốt',
                'detail'=>'Hàng bên em tốt miễn bàn',
                'colors'=>1,
                'sizes'=>1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
                'status' => 1
            ]
        ]);
    }
}
